[versions]

compileSdk = "36"
targetSdk = "36"
minSdk = "23"

kotlin-lang = "2.2.21"
compose-multiplatform = "1.9.3"

kotlin-serialization = "1.9.0"
androidx-activityCompose = "1.12.2"
androidx-activityComposeCatalog = "1.12.2"
androidx-core = "1.17.0"

[libraries]

kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-lang" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-lang" }
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialization" }
agp = "com.android.tools.build:gradle:8.13.2"
androidx-appCompat = "androidx.appcompat:appcompat:1.7.1"
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-activityComposeCatalog = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityComposeCatalog" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-customView = { module = "androidx.customview:customview", version = "1.2.0" }
androidx-customViewPoolingContainer = { module = "androidx.customview:customview-poolingcontainer", version = "1.1.0" }
coil = { module = "io.coil-kt.coil3:coil-compose", version = "3.3.0" }
stately = { module = "co.touchlab:stately-concurrency", version = "2.1.0" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-animationGraphics = { module = "androidx.compose.animation:animation-graphics" }
compose-bom = "androidx.compose:compose-bom:2025.12.01"
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material3 = "androidx.compose.material3:material3:1.4.0"
compose-materialRipple = { module = "androidx.compose.material:material-ripple" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.9.6" }
compose-navigation-multiplatform = { module = "org.jetbrains.androidx.navigation:navigation-compose", version = "2.9.1" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uiUtil = { module = "androidx.compose.ui:ui-util" }
vannitktech-mavenPublish-gradle = "com.vanniktech:gradle-maven-publish-plugin:0.35.0"

[plugins]
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version = "1.0.0-beta06" }

[bundles]
